AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Style/FrozenStringLiteralComment:
  Exclude:
    - spec/**/*
